{{- if .Values.spec.global.networkPolicy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "app.fullname" . }}-default
  namespace: {{ .Values.spec.global.namespace }}
  labels:
    {{- include "app.commonLabels" . | nindent 4 }}
    {{- with .Values.spec.global.labels }}
{{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  {{- if .Values.spec.global.networkPolicy.ingress }}
  ingress:
{{ toYaml .Values.spec.global.networkPolicy.ingress | nindent 2 }}
  {{- else }}
  ingress: []
  {{- end }}
  {{- if .Values.spec.global.networkPolicy.egress }}
  egress:
{{ toYaml .Values.spec.global.networkPolicy.egress | nindent 2 }}
  {{- else }}
  egress: []
  {{- end }}
{{- end }}

