{{- if .Values.spec.global.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "app.fullname" .) .Values.spec.global.serviceAccount.name }}
  namespace: {{ .Values.spec.global.namespace }}
  labels:
    {{- include "app.commonLabels" . | nindent 4 }}
    {{- with .Values.spec.global.labels }}
{{ toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.spec.global.serviceAccount.annotations }}
  annotations:
{{ toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

